server:
  port: 8081
  address: 0.0.0.0

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/driver_db?useSSL=false&serverTimezone=UTC
    username: root
    password: 1234
  application:
    name: driver-system

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
